<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kelompok 2">

<title>Tugas MDS - MongoDB</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Kelompok 2 Mongo DB_files/libs/clipboard/clipboard.min.js"></script>
<script src="Kelompok 2 Mongo DB_files/libs/quarto-html/quarto.js"></script>
<script src="Kelompok 2 Mongo DB_files/libs/quarto-html/popper.min.js"></script>
<script src="Kelompok 2 Mongo DB_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Kelompok 2 Mongo DB_files/libs/quarto-html/anchor.min.js"></script>
<link href="Kelompok 2 Mongo DB_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Kelompok 2 Mongo DB_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Kelompok 2 Mongo DB_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Kelompok 2 Mongo DB_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Kelompok 2 Mongo DB_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tugas MDS - MongoDB</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kelompok 2 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="anggota-kelompok" class="level2">
<h2 class="anchored" data-anchor-id="anggota-kelompok">Anggota Kelompok :</h2>
<p>Dela Gustiara - M0501241024</p>
<p>Rizka Annisa Mingka - M0501241041</p>
<p>Windi Pangesti -M0501241022</p>
<p>Wildatul Maulidiyah -M0501241091</p>
</section>
<section id="analisis-film-imdb-global-20202025-dengan-mongodb-dan-r" class="level1">
<h1>Analisis Film IMDb Global 2020–2025 dengan MongoDB dan R</h1>
<section id="menghubungkan-dengan-mongodb" class="level2">
<h2 class="anchored" data-anchor-id="menghubungkan-dengan-mongodb">Menghubungkan Dengan MongoDB</h2>
<section id="memuat-library" class="level3">
<h3 class="anchored" data-anchor-id="memuat-library">Memuat Library</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ readr     2.1.5
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mongolite)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wordcloud)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: RColorBrewer</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: NLP

Attaching package: 'NLP'

The following object is masked from 'package:ggplot2':

    annotate</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mengimpor berbagai library yang digunakan untuk manipulasi data, koneksi ke MongoDB, dan visualisasi:</p>
<ul>
<li><p><code>readxl</code>: membaca file Excel</p></li>
<li><p><code>dplyr</code>, <code>tidyverse</code>: manipulasi data</p></li>
<li><p><code>stringr</code>: pemrosesan string</p></li>
<li><p><code>mongolite</code>: koneksi ke MongoDB Atlas dan lokal</p></li>
<li><p><code>tm</code>, <code>wordcloud</code>, <code>RColorBrewer</code>: untuk membuat word cloud dari judul film</p></li>
</ul>
</section>
<section id="membaca-dan-menampilkan-data" class="level3">
<h3 class="anchored" data-anchor-id="membaca-dan-menampilkan-data">Membaca dan Menampilkan Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"Data_20202025.xlsx"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 645 × 6
   Title                                    Year  Duration Rating Vote  Category
   &lt;chr&gt;                                    &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;   
 1 Final Destination: Bloodlines            2025  1h 50m   7.1    28K   R       
 2 Nonnas                                   2025  1h 51m   6.9    17K   PG      
 3 Sinners                                  2025  2h 17m   8.1    104K  R       
 4 Thunderbolts*                            2025  2h 7m    7.6    95K   PG-13   
 5 Mission: Impossible - The Final Reckoni… 2025  2h 49m   7.6    19K   PG-13   
 6 A Minecraft Movie                        2025  1h 41m   5.8    92K   PG      
 7 Hurry Up Tomorrow                        2025  1h 45m   5.2    5.8K  R       
 8 Snow White                               2025  1h 49m   1.7    358K  PG      
 9 A Working Man                            2025  1h 56m   5.7    39K   R       
10 Warfare                                  2025  1h 35m   7.4    38K   R       
# ℹ 635 more rows</code></pre>
</div>
</div>
<p>Membaca file Excel berisi data film dan menampilkannya.</p>
</section>
<section id="membersihkan-dan-mengubah-data" class="level3">
<h3 class="anchored" data-anchor-id="membersihkan-dan-mengubah-data">Membersihkan dan Mengubah Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">DurationMinutes =</span> <span class="fu">ifelse</span>(<span class="fu">str_detect</span>(Duration, <span class="st">"h"</span>), <span class="fu">as.numeric</span>(<span class="fu">str_extract</span>(Duration, <span class="st">"</span><span class="sc">\\</span><span class="st">d+(?=h)"</span>)) <span class="sc">*</span> <span class="dv">60</span>, <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">ifelse</span>(<span class="fu">str_detect</span>(Duration, <span class="st">"m"</span>), <span class="fu">as.numeric</span>(<span class="fu">str_extract</span>(Duration, <span class="st">"</span><span class="sc">\\</span><span class="st">d+(?=m)"</span>)), <span class="dv">0</span>),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">VoteClean =</span> Vote <span class="sc">%&gt;%</span> <span class="fu">str_trim</span>() <span class="sc">%&gt;%</span> <span class="fu">str_replace_all</span>(<span class="st">","</span>, <span class="st">"."</span>),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">VoteNumeric =</span> <span class="fu">case_when</span>(</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(VoteClean, <span class="st">"K"</span>) <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">str_remove</span>(VoteClean, <span class="st">"K"</span>)) <span class="sc">*</span> <span class="fl">1e3</span>,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(VoteClean, <span class="st">"M"</span>) <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">str_remove</span>(VoteClean, <span class="st">"M"</span>)) <span class="sc">*</span> <span class="fl">1e6</span>,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="fu">as.numeric</span>(VoteClean)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Title, Year, DurationMinutes, Rating, VoteNumeric, Category)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There were 2 warnings in `mutate()`.
The first warning was:
ℹ In argument: `VoteNumeric = case_when(...)`.
Caused by warning:
! NAs introduced by coercion
ℹ Run `dplyr::last_dplyr_warnings()` to see the 1 remaining warning.</code></pre>
</div>
</div>
<ul>
<li><p>Membersihkan dan mengonversi kolom:</p>
<ul>
<li><p><code>Duration</code>: Diubah dari jam dan menit ke total menit.</p></li>
<li><p><code>Vote</code>: Diubah dari format teks “1.5K”, “2M”, dll ke angka (<code>VoteNumeric</code>)</p></li>
</ul></li>
</ul>
</section>
<section id="menyimpan-data" class="level3">
<h3 class="anchored" data-anchor-id="menyimpan-data">Menyimpan Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(df_clean, <span class="st">"imdb_global_final.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Menyimpan data yang sudah dibersihkan ke file CSV.</li>
</ul>
</section>
<section id="koneksi-ke-mongodb-atlas" class="level3">
<h3 class="anchored" data-anchor-id="koneksi-ke-mongodb-atlas">Koneksi ke MongoDB Atlas</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Connect to MongoDB Atlas</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'Connecting to MongoDB Atlas'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Connecting to MongoDB Atlas</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>atlas_conn <span class="ot">&lt;-</span> <span class="fu">mongo</span>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">collection =</span> <span class="st">"film_imdb"</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">db =</span> <span class="st">"filmkita"</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">url =</span> <span class="st">"mongodb+srv://wildatulmaulidiyah:Wilda1519*@cluster0.oct4afj.mongodb.net/?retryWrites=true&amp;w=majority&amp;appName=Cluster0"</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if connection is working</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (atlas_conn<span class="sc">$</span><span class="fu">count</span>() <span class="sc">&gt;=</span> <span class="dv">0</span>) {</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">message</span>(<span class="st">"Successfully connected to MongoDB Atlas"</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">message</span>(<span class="st">"Failed to connect to MongoDB Atlas"</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Successfully connected to MongoDB Atlas</code></pre>
</div>
</div>
<ul>
<li><p><code>collection = "film_imdb"</code>: Koleksi atau tabel tempat data akan disimpan.</p></li>
<li><p><code>db = "filmkita"</code>: Nama database di MongoDB Atlas.</p></li>
<li><p><code>url =</code>: Alamat koneksi ke cluster MongoDB Atlas yang telah dikonfigurasi dengan akun dan database yang sesuai.</p>
<p>MongoDB Atlas digunakan agar data dapat disimpan dan diakses secara online melalui cloud.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Insert data into MongoDB</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'Inserting data into MongoDB'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Inserting data into MongoDB</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>insert_result <span class="ot">&lt;-</span> atlas_conn<span class="sc">$</span><span class="fu">insert</span>(df_clean)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(insert_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 5
 $ nInserted  : num 645
 $ nMatched   : num 0
 $ nRemoved   : num 0
 $ nUpserted  : num 0
 $ writeErrors: list()</code></pre>
</div>
</div>
<p>Menyimpan seluruh data <code>df_clean</code> ke dalam koleksi di MongoDB Atlas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>retrieved_data <span class="ot">&lt;-</span> atlas_conn<span class="sc">$</span><span class="fu">find</span>(<span class="at">limit =</span> <span class="dv">5</span>)  <span class="co"># Just get first 5 records as a sample</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(retrieved_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                      Title Year DurationMinutes Rating
1             Final Destination: Bloodlines 2025             110    7.1
2                                    Nonnas 2025             111    6.9
3                                   Sinners 2025             137    8.1
4                             Thunderbolts* 2025             127    7.6
5 Mission: Impossible - The Final Reckoning 2025             169    7.6
  VoteNumeric Category
1       28000        R
2       17000       PG
3      104000        R
4       95000    PG-13
5       19000    PG-13</code></pre>
</div>
</div>
<p>Menyimpan seluruh data <code>df_clean</code> ke dalam koleksi di MongoDB Atlas.</p>
</section>
<section id="koneksi-mongodb-lokal" class="level3">
<h3 class="anchored" data-anchor-id="koneksi-mongodb-lokal">Koneksi MongoDB Lokal</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Koneksi ke MongoDB lokal</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>mongo_conn <span class="ot">&lt;-</span> <span class="fu">mongo</span>(<span class="at">collection =</span> <span class="st">"imdb_global"</span>, <span class="at">db =</span> <span class="st">"film_db"</span>, <span class="at">url =</span> <span class="st">"mongodb://localhost:27017"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Hapus koleksi sebelumnya (jika ingin bersih)</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>mongo_conn<span class="sc">$</span><span class="fu">drop</span>()</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Masukkan data ke MongoDB</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>mongo_conn<span class="sc">$</span><span class="fu">insert</span>(df_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 5
 $ nInserted  : num 645
 $ nMatched   : num 0
 $ nRemoved   : num 0
 $ nUpserted  : num 0
 $ writeErrors: list()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>mongo_conn<span class="sc">$</span><span class="fu">count</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 645</code></pre>
</div>
</div>
<ul>
<li><p><code>collection = "imdb_global"</code>: Koleksi lokal untuk menyimpan data.</p></li>
<li><p><code>db = "film_db"</code>: Nama database lokal.</p></li>
<li><p><code>url = "mongodb://localhost:27017"</code>: Koneksi ke server MongoDB yang berjalan secara lokal di komputer.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ambil data dari MongoDB</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> mongo_conn<span class="sc">$</span><span class="fu">find</span>()</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Pastikan konversi ke numerik</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>df_clean<span class="sc">$</span>VoteNumeric <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df_clean<span class="sc">$</span>VoteNumeric)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>df_clean<span class="sc">$</span>Rating <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df_clean<span class="sc">$</span>Rating)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>df_clean<span class="sc">$</span>DurationMinutes <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df_clean<span class="sc">$</span>DurationMinutes)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                      Title Year DurationMinutes Rating
1             Final Destination: Bloodlines 2025             110    7.1
2                                    Nonnas 2025             111    6.9
3                                   Sinners 2025             137    8.1
4                             Thunderbolts* 2025             127    7.6
5 Mission: Impossible - The Final Reckoning 2025             169    7.6
6                         A Minecraft Movie 2025             101    5.8
  VoteNumeric Category
1       28000        R
2       17000       PG
3      104000        R
4       95000    PG-13
5       19000    PG-13
6       92000       PG</code></pre>
</div>
</div>
<ul>
<li><p><code>df_clean &lt;- mongo_conn$find():</code>Perintah ini mengambil seluruh dokumen dari koleksi MongoDB yang terhubung melalui objek <code>mongo_conn</code>, lalu menyimpannya dalam bentuk data frame <code>df_clean</code> di R.</p></li>
<li><p><code>df_clean$VoteNumeric &lt;- as.numeric(df_clean$VoteNumeric):</code>Mengubah kolom jumlah suara ke bentuk angka, penting untuk analisis kuantitatif popularitas film.</p></li>
</ul>
<!-- -->
<ul>
<li><p><code>df_clean$Rating &lt;- as.numeric(df_clean$Rating):</code>Mengubah skor rating (biasanya dari IMDb) menjadi nilai numerik untuk dianalisis secara statistik seperti rata-rata atau distribusi.</p></li>
<li><p><code>df_clean$DurationMinutes &lt;- as.numeric(df_clean$DurationMinutes):</code>Mengubah durasi film ke dalam angka agar dapat dihitung, dirata-ratakan, atau divisualisasikan dalam grafik durasi.</p></li>
</ul>
</section>
</section>
<section id="mencoba-melakukan-agregasi-data" class="level2">
<h2 class="anchored" data-anchor-id="mencoba-melakukan-agregasi-data">Mencoba Melakukan Agregasi Data</h2>
<section id="menghitung-rata-rata-rting-dan-total-vote-per-tahun" class="level3">
<h3 class="anchored" data-anchor-id="menghitung-rata-rata-rting-dan-total-vote-per-tahun">Menghitung Rata-rata Rting dan Total Vote Per Tahun</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>pipeline_avg_rating_vote <span class="ot">&lt;-</span> <span class="st">'[</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="st">  {</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="st">    "$group": {</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="st">      "_id": "$Year",</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="st">      "avgRating": { "$avg": "$Rating" },</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="st">      "totalVotes": { "$sum": "$VoteNumeric" },</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="st">      "count": { "$sum": 1 }</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="st">    }</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="st">  },</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="st">  {</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="st">    "$sort": { "_id": 1 }</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="st">  }</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="st">]'</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>result_avg_rating_vote <span class="ot">&lt;-</span> mongo_conn<span class="sc">$</span><span class="fu">aggregate</span>(pipeline_avg_rating_vote)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_avg_rating_vote)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   _id avgRating totalVotes count
1 2020        NA    4859200    34
2 2021        NA   12195900    55
3 2022        NA   14045869    78
4 2023        NA   14274424   119
5 2024        NA   11645310   209
6 2025        NA    2427231   150</code></pre>
</div>
</div>
<p>Mengelompokkan data berdasarkan tahun (<code>Year</code>), menghitung:</p>
<ul>
<li><p>rata-rata rating film per tahun (<code>avgRating</code>),</p></li>
<li><p>total jumlah vote per tahun (<code>totalVotes</code>),</p></li>
<li><p>jumlah film per tahun (<code>count</code>).</p></li>
</ul>
<p>Penggunaan agregasi untuk mengetahui tren kualitas dan popularitas film tiap tahun.</p>
</section>
<section id="jumlah-film-per-kategori" class="level3">
<h3 class="anchored" data-anchor-id="jumlah-film-per-kategori">Jumlah Film per Kategori</h3>
<p>Menghitung jumlah film untuk tiap kategori (<code>Category</code>) dan mengurutkan dari yang paling banyak. Berguna untuk mengetahui kategori film yang paling populer atau paling banyak diproduksi.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>pipeline_count_category <span class="ot">&lt;-</span> <span class="st">'[</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="st">  {</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="st">    "$group": {</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="st">      "_id": "$Category",</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="st">      "totalFilms": { "$sum": 1 }</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="st">    }</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="st">  },</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="st">  {</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="st">    "$sort": { "totalFilms": -1 }</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="st">  }</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="st">]'</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>result_count_category <span class="ot">&lt;-</span> mongo_conn<span class="sc">$</span><span class="fu">aggregate</span>(pipeline_count_category)</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_count_category)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         _id totalFilms
1          R        302
2      PG-13        150
3       &lt;NA&gt;         92
4         PG         43
5  Not Rated         20
6      TV-MA         19
7      TV-14          9
8    Unrated          5
9      TV-PG          3
10       16+          1
11     NC-17          1</code></pre>
</div>
</div>
</section>
<section id="durasi-film-terlama-dan-terpendek-per-tahun" class="level3">
<h3 class="anchored" data-anchor-id="durasi-film-terlama-dan-terpendek-per-tahun">Durasi Film Terlama dan Terpendek per Tahun</h3>
<p>Pada bagian ini mencoba untuk mengelompokkan film berdasarkan tahun dan mengambil durasi maksimum (<code>maxDuration</code>) dan minimum (<code>minDuration</code>) per tahun. Ini berguna untuk melihat variasi durasi film dalam tiap tahun.</p>
</section>
<section id="rata-rata-rating-dan-jumlah-vote-per-kategori" class="level3">
<h3 class="anchored" data-anchor-id="rata-rata-rating-dan-jumlah-vote-per-kategori">Rata-rata Rating dan Jumlah Vote Per Kategori</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>pipeline_duration_extremes <span class="ot">&lt;-</span> <span class="st">'[</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="st">  {</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="st">    "$group": {</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="st">      "_id": "$Year",</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="st">      "maxDuration": { "$max": "$DurationMinutes" },</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="st">      "minDuration": { "$min": "$DurationMinutes" }</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="st">    }</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="st">  },</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="st">  {</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="st">    "$sort": { "_id": 1 }</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="st">  }</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="st">]'</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>result_duration_extremes <span class="ot">&lt;-</span> mongo_conn<span class="sc">$</span><span class="fu">aggregate</span>(pipeline_duration_extremes)</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_duration_extremes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   _id maxDuration minDuration
1 2020         160          88
2 2021         242          83
3 2022         192          86
4 2023         206          85
5 2024         216          84
6 2025         169           0</code></pre>
</div>
</div>
</section>
<section id="rata-rata-rating-dan-jumlah-vote-per-kategori-1" class="level3">
<h3 class="anchored" data-anchor-id="rata-rata-rating-dan-jumlah-vote-per-kategori-1">Rata-rata Rating dan Jumlah Vote Per Kategori</h3>
<p>Bagian ini bertujuan untuk mengetahui rata rata rating pada setiap film per kategori dengan mengelompokkan berdasarkan genre (<code>Category</code>), menghitung rata-rata rating dan total vote serta jumlah film per genre. Hasil ini membantu mengetahui genre film dengan rating terbaik dan jumlah vote terbanyak.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>pipeline_avg_rating_vote_category <span class="ot">&lt;-</span> <span class="st">'[</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="st">  {</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="st">    "$group": {</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="st">      "_id": "$Category",</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="st">      "avgRating": { "$avg": "$Rating" },</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="st">      "totalVotes": { "$sum": "$VoteNumeric" },</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="st">      "count": { "$sum": 1 }</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="st">    }</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="st">  },</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="st">  {</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="st">    "$sort": { "avgRating": -1 }</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="st">  }</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a><span class="st">]'</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>result_avg_rating_vote_category <span class="ot">&lt;-</span> mongo_conn<span class="sc">$</span><span class="fu">aggregate</span>(pipeline_avg_rating_vote_category)</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_avg_rating_vote_category)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         _id avgRating totalVotes count
1      NC-17        NA      76000     1
2      TV-PG        NA      23479     3
3       &lt;NA&gt;        NA     706377    92
4    Unrated        NA      70148     5
5         PG        NA    4739700    43
6        16+        NA      10000     1
7      TV-14        NA     169207     9
8      TV-MA        NA     576970    19
9      PG-13        NA   24861623   150
10 Not Rated        NA     699200    20
11         R        NA   27515230   302</code></pre>
</div>
</div>
<p>Top 5 Film dengan Rating Tertinggi per Tahun</p>
<p>Berdasarkan hasil agregasi yang telah dilakukan, berikut merupakan syntax untuk mengurutkan film berdasarkan tahun dan rating tertinggi, lalu mengelompokkan per tahun dan mengambil 5 film terbaik. Mempermudah menemukan film top di setiap tahun.</p>
</section>
</section>
<section id="visualisasi-data" class="level2">
<h2 class="anchored" data-anchor-id="visualisasi-data">Visualisasi Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>pipeline_top5_rating_per_year <span class="ot">&lt;-</span> <span class="st">'[</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="st">  {</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="st">    "$sort": { "Year": 1, "Rating": -1 }</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="st">  },</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="st">  {</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="st">    "$group": {</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="st">      "_id": "$Year",</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="st">      "topFilms": {</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="st">        "$push": { "Title": "$Title", "Rating": "$Rating", "VoteNumeric": "$VoteNumeric" }</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="st">      }</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="st">    }</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a><span class="st">  },</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a><span class="st">  {</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="st">    "$project": {</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="st">      "topFilms": { "$slice": ["$topFilms", 5] }</span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a><span class="st">    }</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a><span class="st">  }</span></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a><span class="st">]'</span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>result_top5_rating_per_year <span class="ot">&lt;-</span> mongo_conn<span class="sc">$</span><span class="fu">aggregate</span>(pipeline_top5_rating_per_year)</span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_top5_rating_per_year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   _id
1 2024
2 2021
3 2025
4 2020
5 2023
6 2022
                                                                                                                                                                      topFilms
1 Attack on Titan the Movie: The Last Attack, Solo Leveling: ReAwakening, Dune: Part Two, Maharaja, No Other Land, 9.2, 8.8, 8.5, 8.4, 8.3, 17000, 13000, 632000, 69000, 13000
2  Spider-Man: No Way Home, Dune: Part One, CODA, Zack Snyder's Justice League, The Worst Person in the World, 8.2, 8.0, 8.0, 7.9, 7.7, 953000, 958000, 178000, 456000, 111000
3                      Guru Nanak Jahaz, Ocean with David Attenborough, Tourist Family, Dangerous Animals, Eleanor the Great, 9.4, 8.7, 8.6, 8.4, 8.3, 3400, 558, 2200, 46, 57
4                                            Hamilton, The Father, Soul, Another Round, Promising Young Woman, 8.3, 8.2, 8.0, 7.7, 7.5, 128000, 213000, 409000, 213000, 225000
5                           12th Fail, Spider-Man: Across the Spider-Verse, Oppenheimer, Better Half, Perfect Days, 8.7, 8.5, 8.3, 8.1, 7.9, 148000, 457000, 893000, 35, 84000
6            Top Gun: Maverick, All Quiet on the Western Front, Puss in Boots: The Last Wish, The Batman, RRR, 8.2, 7.8, 7.8, 7.8, 7.8, 777000, 274000, 205000, 872000, 179000</code></pre>
</div>
</div>
</section>
<section id="visualisasi-data-1" class="level2">
<h2 class="anchored" data-anchor-id="visualisasi-data-1">Visualisasi Data</h2>
<section id="top-5-film-berdasarkan-rating" class="level3">
<h3 class="anchored" data-anchor-id="top-5-film-berdasarkan-rating">Top 5 Film Berdasarkan Rating</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Rating)) <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Title, Rating), <span class="at">y =</span> Rating, <span class="at">fill =</span> Title)) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Rating), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Top 5 Film Berdasarkan Rating"</span>, <span class="at">x =</span> <span class="st">"Judul Film"</span>, <span class="at">y =</span> <span class="st">"Rating"</span>) <span class="sc">+</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Plot “Top 5 Film Berdasarkan Rating” menampilkan lima film dengan penilaian tertinggi dari penonton. <em>Guru Nanak Jahaz</em> menempati peringkat pertama dengan rating 9.4, diikuti <em>Attack on Titan the Movie: The Last Attack</em> (9.2) dan <em>Solo Leveling: ReAwakening</em> (8.8), menunjukkan dominasi film animasi dan aksi. Sementara itu, <em>Ocean with David Attenborough</em> dan <em>12th Fail</em> sama-sama meraih 8.7, membuktikan bahwa dokumenter edukatif dan drama inspiratif juga mendapat apresiasi tinggi. Grafik ini mencerminkan keragaman genre yang diminati penonton, mulai dari animasi hingga dokumenter, serta menunjukkan minat yang semakin luas terhadap berbagai bentuk narasi, baik hiburan maupun edukatif.</p>
</section>
<section id="top-5-film-berdasarkan-jumlah-vote" class="level3">
<h3 class="anchored" data-anchor-id="top-5-film-berdasarkan-jumlah-vote">Top 5 Film Berdasarkan Jumlah Vote</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'scales'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    discard</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:readr':

    col_factor</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(VoteNumeric)) <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Title, VoteNumeric), <span class="at">y =</span> VoteNumeric, <span class="at">fill =</span> Title)) <span class="sc">+</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">comma</span>(VoteNumeric)), </span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>, </span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">clip =</span> <span class="st">"off"</span>) <span class="sc">+</span>  <span class="co"># mencegah pemotongan label</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Top 5 Film Berdasarkan Jumlah Vote"</span>,</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Judul Film"</span>,</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Jumlah Vote"</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>(<span class="at">clip =</span> <span class="st">"off"</span>) <span class="sc">+</span>  <span class="co"># penting agar teks bisa keluar dari area panel</span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="fl">5.5</span>, <span class="dv">30</span>, <span class="fl">5.5</span>, <span class="fl">5.5</span>)  <span class="co"># tambah margin kanan</span></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>)))  <span class="co"># beri ruang di ujung kanan</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_text(aes(label = comma(VoteNumeric)), hjust = -0.1, clip =
"off"): Ignoring unknown parameters: `clip`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Plot “Top 5 Film Berdasarkan Jumlah Vote” menunjukkan film-film dengan popularitas tertinggi berdasarkan partisipasi penonton. <em>Dune: Part One</em> dan <em>Spider-Man: No Way Home</em> menempati posisi teratas dengan jumlah vote hampir sejajar, menunjukkan antusiasme tinggi. <em>Oppenheimer</em>, <em>The Batman</em>, dan <em>Top Gun: Maverick</em> juga meraih vote signifikan, mencerminkan daya tarik film bertema sejarah, superhero, dan aksi klasik.</p>
<p>Jika dibandingkan dengan plot “Top 5 Film Berdasarkan Rating”, terlihat perbedaan antara film dengan rating tinggi dan film dengan jumlah vote terbanyak. Film seperti <em>Guru Nanak Jahaz</em> dan <em>Solo Leveling</em> mendapat rating tinggi namun tidak muncul dalam daftar vote terbanyak, menandakan apresiasi kualitas oleh segmen tertentu. Sebaliknya, film-film dengan jumlah vote tinggi lebih mencerminkan daya jangkau luas dan popularitas massal. Hal ini menegaskan bahwa film yang paling disukai belum tentu yang paling banyak ditonton, dan sebaliknya.</p>
</section>
<section id="boxplot-sebaran-durasi-film" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-sebaran-durasi-film">Boxplot Sebaran Durasi Film</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_clean, <span class="fu">aes</span>(<span class="at">y =</span> DurationMinutes)) <span class="sc">+</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"#FF7F0E"</span>) <span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sebaran Durasi Film (Menit)"</span>, <span class="at">y =</span> <span class="st">"Durasi (menit)"</span>) <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Boxplot berjudul “Sebaran Durasi Film (Menit)” menggambarkan distribusi panjang film yang umumnya berkisar antara 100 hingga 130 menit, dengan nilai tengah (median) berada di sekitar 110 menit. Ini menunjukkan bahwa sebagian besar film memiliki durasi sekitar 1,5 hingga 2 jam, yang merupakan standar umum dalam industri perfilman. Di luar rentang ini, terdapat beberapa outlier, yakni film-film dengan durasi sangat panjang hingga lebih dari 240 menit, serta satu film berdurasi sangat pendek yang mendekati 0 menit. Kehadiran outlier ini mencerminkan bahwa meskipun mayoritas film mengikuti pola durasi konvensional, ada juga film-film yang menawarkan pengalaman menonton di luar kebiasaan, baik berupa film pendek maupun epik berdurasi panjang. Sebaran yang sedikit condong ke atas juga menunjukkan bahwa variasi durasi lebih besar terjadi pada film-film yang berdurasi panjang dibandingkan yang berdurasi pendek.</p>
</section>
<section id="top-3-film-berdurasi-terlama" class="level3">
<h3 class="anchored" data-anchor-id="top-3-film-berdurasi-terlama">Top 3 Film Berdurasi Terlama</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(DurationMinutes)) <span class="sc">%&gt;%</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Title, DurationMinutes), <span class="at">y =</span> DurationMinutes, <span class="at">fill =</span> Title)) <span class="sc">+</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(DurationMinutes, <span class="st">" min"</span>)), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">clip =</span> <span class="st">"off"</span>) <span class="sc">+</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"3 Film dengan Durasi Terlama"</span>, <span class="at">x =</span> <span class="st">"Judul Film"</span>, <span class="at">y =</span> <span class="st">"Durasi (menit)"</span>) <span class="sc">+</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>(<span class="at">clip =</span> <span class="st">"off"</span>) <span class="sc">+</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="fl">5.5</span>, <span class="dv">30</span>, <span class="fl">5.5</span>, <span class="fl">5.5</span>)) <span class="sc">+</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_text(aes(label = paste0(DurationMinutes, " min")), hjust =
-0.1, : Ignoring unknown parameters: `clip`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Plot “3 Film dengan Durasi Terlama” menunjukkan tiga film yang memiliki waktu tayang paling panjang dalam daftar. Di posisi teratas adalah <em>Zack Snyder’s Justice League</em> dengan durasi luar biasa mencapai 242 menit (lebih dari 4 jam), menjadikannya sebagai film dengan durasi terlama. Film ini memang dikenal sebagai versi penyutradaraan ulang yang jauh lebih panjang dibanding versi aslinya.</p>
<p>Di bawahnya, terdapat <em>The Brutalist</em> dengan durasi 216 menit, dan <em>Killers of the Flower Moon</em> dengan 206 menit. Kedua film ini juga menampilkan narasi mendalam dan cenderung kompleks, yang membutuhkan waktu tayang lebih lama untuk mengembangkan cerita secara utuh.</p>
<p>Secara keseluruhan, visualisasi ini menyoroti bahwa meskipun film berdurasi panjang cenderung jarang, mereka tetap memiliki tempat tersendiri dalam industri perfilman terutama untuk karya-karya dengan tema serius, narasi mendalam, atau versi director’s cut yang ingin memberikan pengalaman sinematik lebih lengkap kepada penonton.</p>
</section>
<section id="korelasi-rating-dengan-jumlah-vote" class="level3">
<h3 class="anchored" data-anchor-id="korelasi-rating-dengan-jumlah-vote">Korelasi Rating dengan Jumlah Vote</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_clean, <span class="fu">aes</span>(<span class="at">x =</span> VoteNumeric, <span class="at">y =</span> Rating)) <span class="sc">+</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Korelasi Rating dan Jumlah Vote"</span>, <span class="at">x =</span> <span class="st">"Jumlah Vote"</span>, <span class="at">y =</span> <span class="st">"Rating"</span>) <span class="sc">+</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Plot “Korelasi Rating dan Jumlah Vote” menunjukkan hubungan antara rating film dan jumlah suara (vote) yang diberikan oleh penonton. Titik-titik biru merepresentasikan film individual, sedangkan garis hitam menunjukkan tren umum hubungan antara kedua variabel. Secara keseluruhan, terlihat korelasi positif lemah: semakin banyak vote yang diterima sebuah film, cenderung semakin tinggi pula ratingnya, meskipun tidak mutlak. Sebagian besar film berada pada rentang vote rendah (di bawah 100.000), dengan rating bervariasi antara 5 hingga 8. Namun, film-film dengan jumlah vote sangat tinggi (lebih dari 500.000) umumnya memiliki rating di atas rata-rata, yakni sekitar 7 ke atas. Hal ini mengindikasikan bahwa film yang populer atau banyak ditonton juga cenderung disukai oleh penonton secara umum.</p>
<p>Meski demikian, sebaran data cukup menyebar, terutama pada film dengan sedikit vote yang memiliki rating sangat bervariasi, dari sangat rendah hingga sangat tinggi. Ini menunjukkan bahwa rating pada film dengan sedikit vote mungkin kurang stabil atau representatif. Dengan kata lain, film dengan basis penonton yang lebih besar cenderung memiliki rating yang lebih konsisten dan sedikit lebih tinggi. Korelasi ini penting untuk dipahami, terutama dalam konteks menilai kualitas film berdasarkan popularitas dan keterlibatan audiens</p>
</section>
<section id="korelasi-durasi-dengan-rating" class="level3">
<h3 class="anchored" data-anchor-id="korelasi-durasi-dengan-rating">Korelasi Durasi dengan Rating</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_clean, <span class="fu">aes</span>(<span class="at">x =</span> DurationMinutes, <span class="at">y =</span> Rating)) <span class="sc">+</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Korelasi Durasi dan Rating"</span>, <span class="at">x =</span> <span class="st">"Durasi (menit)"</span>, <span class="at">y =</span> <span class="st">"Rating"</span>) <span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Berdasarkan plot yang ditampilkan, terlihat adanya hubungan positif antara durasi film (dalam menit) dan rating film, yang ditunjukkan oleh garis tren yang menaik. Artinya, secara umum, film dengan durasi yang lebih panjang cenderung memiliki rating yang lebih tinggi dibandingkan dengan film berdurasi pendek. Namun, pola penyebaran titik-titik data yang cukup menyebar dari garis tren menunjukkan bahwa hubungan ini tidak terlalu kuat. Banyak film berdurasi pendek yang memiliki rating tinggi, begitu juga sebaliknya, menunjukkan adanya variabilitas yang tinggi pada data. Oleh karena itu, meskipun arah hubungan bersifat positif, kekuatan korelasinya tergolong lemah. Hal ini mengindikasikan bahwa durasi film bukanlah satu-satunya atau faktor utama yang memengaruhi penilaian rating sebuah film, dan kemungkinan terdapat faktor-faktor lain yang lebih dominan dalam menentukan rating.</p>
</section>
<section id="heatmap-korelasi-variabel-numerik" class="level3">
<h3 class="anchored" data-anchor-id="heatmap-korelasi-variabel-numerik">Heatmap Korelasi Variabel Numerik</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.95 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ambil hanya variabel numerik</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>num_data <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(DurationMinutes, Rating, VoteNumeric) <span class="sc">%&gt;%</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Buat matriks korelasi</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(num_data)</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Tampilkan heatmap penuh</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">method =</span> <span class="st">"color"</span>, <span class="at">type =</span> <span class="st">"full"</span>,</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">addCoef.col =</span> <span class="st">"black"</span>,        <span class="co"># tampilkan nilai korelasi</span></span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.cex =</span> <span class="dv">1</span>,                   <span class="co"># ukuran label</span></span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">number.cex =</span> <span class="fl">0.9</span>,             <span class="co"># ukuran angka korelasi</span></span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"white"</span>, <span class="st">"red"</span>))(<span class="dv">200</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Berdasarkan matriks korelasi Pearson, terdapat hubungan positif antara durasi film (<code>DurationMinutes</code>), rating (<code>Rating</code>), dan jumlah suara (<code>VoteNumeric</code>). Korelasi antara durasi dan rating sebesar 0.32 menunjukkan hubungan positif lemah, artinya film berdurasi lebih panjang cenderung memiliki rating sedikit lebih tinggi. Korelasi antara durasi dan jumlah suara sebesar 0.40 menunjukkan hubungan positif sedang, mengindikasikan film berdurasi panjang cenderung mendapat lebih banyak suara. Sementara itu, korelasi antara rating dan jumlah suara sebesar 0.30 juga menunjukkan hubungan positif lemah. Secara keseluruhan, hubungan antar ketiga variabel bersifat positif namun tidak terlalu kuat, sehingga analisis lebih lanjut diperlukan untuk memahami faktor lain yang memengaruhi rating dan popularitas film.</p>
</section>
<section id="rata-rata-rating-film-per-tahun" class="level3">
<h3 class="anchored" data-anchor-id="rata-rata-rating-film-per-tahun">Rata-rata Rating film per Tahun</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">RataRating =</span> <span class="fu">mean</span>(Rating, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Year), <span class="at">y =</span> RataRating)) <span class="sc">+</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#008080"</span>) <span class="sc">+</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(RataRating, <span class="dv">2</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Rata-rata Rating Film per Tahun"</span>, <span class="at">x =</span> <span class="st">"Tahun"</span>, <span class="at">y =</span> <span class="st">"Rating"</span>) <span class="sc">+</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Berdasarkan grafik, rata-rata rating film tertinggi terjadi pada tahun 2020 dan 2021, masing-masing sebesar 6.70 dan 6.67. Kenaikan ini dapat dikaitkan dengan pandemi COVID-19 yang terjadi secara global. Selama masa pandemi, banyak orang menghabiskan waktu di rumah dan mengonsumsi lebih banyak film melalui platform digital, sehingga film-film yang dirilis cenderung lebih terkurasi, berkualitas tinggi, atau memiliki perhatian lebih dari penonton, yang berkontribusi pada rating yang tinggi. Pada tahun 2022 dan 2023, meskipun pandemi mulai mereda, rata-rata rating sedikit menurun namun masih berada di kisaran yang relatif stabil (sekitar 6.6). Hal ini mungkin mencerminkan transisi industri film dari produksi terbatas selama pandemi ke produksi normal kembali, di mana banyak film mulai dirilis kembali secara massal.Penurunan signifikan terjadi pada tahun 2024 dan 2025, dengan rata-rata rating turun menjadi 6.39 dan 6.24. Penurunan ini bisa mencerminkan meningkatnya volume film yang dirilis pasca-pandemi, termasuk banyak produksi dengan kualitas yang bervariasi. Selain itu, ekspektasi penonton yang meningkat seiring kebangkitan industri hiburan bisa menyebabkan penilaian menjadi lebih kritis, sehingga memengaruhi rating secara keseluruhan.</p>
<p>Secara keseluruhan, tren ini menunjukkan bahwa dinamika global dan industri film berpengaruh terhadap penilaian penonton, dengan pandemi memberikan dampak signifikan pada persepsi dan konsumsi film dalam beberapa tahun terakhir.</p>
</section>
<section id="jumlah-film-rilis-per-tahun" class="level3">
<h3 class="anchored" data-anchor-id="jumlah-film-rilis-per-tahun">Jumlah Film Rilis Per Tahun</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Hitung jumlah film per tahun</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>film_per_tahun <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Jumlah =</span> <span class="fu">n</span>())</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot batang jumlah film per tahun</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(film_per_tahun, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Year), <span class="at">y =</span> Jumlah, <span class="at">fill =</span> <span class="fu">factor</span>(Year))) <span class="sc">+</span></span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Jumlah), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>) <span class="sc">+</span></span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"2020"</span> <span class="ot">=</span> <span class="st">"#00d9ff"</span>,</span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"2021"</span> <span class="ot">=</span> <span class="st">"#27c3ff"</span>,</span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"2022"</span> <span class="ot">=</span> <span class="st">"#54a5f7"</span>,</span>
<span id="cb65-16"><a href="#cb65-16" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"2023"</span> <span class="ot">=</span> <span class="st">"#7870f9"</span>,</span>
<span id="cb65-17"><a href="#cb65-17" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"2024"</span> <span class="ot">=</span> <span class="st">"#a051d6"</span>,</span>
<span id="cb65-18"><a href="#cb65-18" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"2025"</span> <span class="ot">=</span> <span class="st">"#cf2a87"</span>)) <span class="sc">+</span></span>
<span id="cb65-19"><a href="#cb65-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb65-20"><a href="#cb65-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Jumlah Film Rilis per Tahun"</span>,</span>
<span id="cb65-21"><a href="#cb65-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb65-22"><a href="#cb65-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="cn">NULL</span></span>
<span id="cb65-23"><a href="#cb65-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb65-24"><a href="#cb65-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb65-25"><a href="#cb65-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb65-26"><a href="#cb65-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb65-27"><a href="#cb65-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb65-28"><a href="#cb65-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb65-29"><a href="#cb65-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb65-30"><a href="#cb65-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()</span>
<span id="cb65-31"><a href="#cb65-31" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Grafik menunjukkan bahwa jumlah film yang dirilis terus meningkat dari tahun 2020 hingga 2024, dengan pertumbuhan yang sangat signifikan. Dimulai dari 34 film pada tahun 2020, jumlah ini melonjak menjadi 209 film pada 2024, yang menjadi puncak tertinggi dalam lima tahun terakhir. Kenaikan ini mencerminkan tren pertumbuhan industri film yang positif, didorong oleh pemulihan pasca-pandemi, peningkatan permintaan penonton, dan ekspansi platform distribusi digital.</p>
<p>Sementara itu, jumlah film yang tercatat pada tahun 2025 telah mencapai 150, meskipun tahun tersebut belum selesai. Fakta ini menunjukkan bahwa tren positif kemungkinan besar akan berlanjut, dan angka akhir tahun berpotensi mendekati atau bahkan melampaui tahun 2024. Dengan demikian, data ini tidak hanya mencerminkan kebangkitan industri film, tetapi juga mengindikasikan momentum yang stabil menuju masa depan yang lebih produktif dan kompetitif dalam dunia perfilman.</p>
</section>
<section id="film-dengan-vote-tertinggi-per-tahun" class="level3">
<h3 class="anchored" data-anchor-id="film-dengan-vote-tertinggi-per-tahun">Film dengan Vote Tertinggi Per Tahun</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> VoteNumeric, <span class="at">n =</span> <span class="dv">1</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Year), <span class="at">y =</span> VoteNumeric, <span class="at">fill =</span> Title)) <span class="sc">+</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Title), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">angle =</span> <span class="dv">20</span>, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Film dengan Vote Tertinggi per Tahun"</span>, <span class="at">x =</span> <span class="st">"Tahun"</span>, <span class="at">y =</span> <span class="st">"Jumlah Vote"</span>) <span class="sc">+</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Grafik menunjukkan bahwa setiap tahun dari 2020 hingga 2025 memiliki film unggulan dengan jumlah vote tertinggi yang mencerminkan kondisi dan respons publik saat itu. Pada 2020, <em>Tenet</em> berhasil meraih sekitar 650.000 vote meski dirilis di tengah pandemi, karena minimnya film besar dan reputasi Christopher Nolan. Tahun 2021 menjadi puncak dengan hampir 1 juta vote untuk <em>Dune: Part One</em>, berkat adaptasi novel legendaris dan strategi rilis ganda. Tahun berikutnya, <em>The Batman</em> (2022) mencatat sekitar 875.000 vote karena pendekatan baru yang lebih gelap dan detektif-sentris. <em>Oppenheimer</em> (2023) menyusul dengan 900.000 vote berkat tema sejarah dan daya tarik Nolan. Namun, <em>Dune: Part Two</em> (2024) mengalami penurunan ke 650.000 vote, diduga karena kejenuhan sekuel dan persaingan ketat. Terakhir, <em>Snow White</em> (2025) hanya meraih sekitar 400.000, hal tersebut dipicu oleh kontroversi seputar casting yang dianggap jauh dari versi klasik serta kritik dari penonton terhadap arah baru disney dalam mengaptasi dongeng lama.</p>
</section>
<section id="jumlah-film-per-kategori-usia" class="level3">
<h3 class="anchored" data-anchor-id="jumlah-film-per-kategori-usia">Jumlah Film per Kategori Usia</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Category)) <span class="sc">%&gt;%</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Category) <span class="sc">%&gt;%</span></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Category, <span class="sc">-</span>n), <span class="at">y =</span> n, <span class="at">fill =</span> Category)) <span class="sc">+</span>  <span class="co"># urutan menurun</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> n), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span>  <span class="co"># label di atas batang</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Jumlah Film per Kategori Usia"</span>, <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Jumlah"</span>) <span class="sc">+</span></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>)</span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Paired"</span>) <span class="sc">+</span>  <span class="co"># gunakan palet warna yang berbeda</span></span>
<span id="cb67-18"><a href="#cb67-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fu">max</span>(df_clean <span class="sc">%&gt;%</span> <span class="fu">count</span>(Category) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(n)) <span class="sc">+</span> <span class="dv">20</span>)  <span class="co"># beri ruang untuk teks</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Grafik “Jumlah Film per Kategori Usia” menunjukkan distribusi film berdasarkan klasifikasi usia. Kategori R (Restricted) mendominasi dengan 302 film, menunjukkan bahwa mayoritas film ditujukan untuk penonton dewasa karena konten yang mungkin mengandung kekerasan, bahasa kasar, atau tema sensitif. Di posisi kedua adalah PG-13 dengan 150 film, yang cocok untuk remaja dan dewasa muda, diikuti oleh PG sebanyak 43 film, yang relatif ramah untuk keluarga.Kategori lainnya seperti Not Rated (20 film) dan TV-MA (19 film) juga muncul, menandakan adanya film yang tidak diklasifikasikan secara resmi atau ditujukan untuk audiens dewasa pada platform televisi/streaming. Kategori seperti TV-14, Unrated, dan TV-PG memiliki jumlah jauh lebih sedikit. Sementara itu, kategori usia ketat seperti NC-17 dan 16+ hanya muncul masing-masing 1 film, menandakan sangat sedikit film yang dibuat untuk kelompok usia yang sangat terbatas. Secara keseluruhan, grafik ini mengindikasikan bahwa industri film lebih banyak memproduksi konten untuk penonton dewasa daripada untuk keluarga atau anak-anak. Hal ini bisa mencerminkan minat pasar, kebebasan kreatif sineas, serta tren konsumsi film yang lebih condong ke genre serius dan dewasa.</p>
</section>
<section id="rata-rata-rating-per-kategori-usia" class="level3">
<h3 class="anchored" data-anchor-id="rata-rata-rating-per-kategori-usia">Rata-rata Rating per Kategori Usia</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Category) <span class="sc">%&gt;%</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">RataRating =</span> <span class="fu">mean</span>(Rating, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Category, <span class="sc">-</span>RataRating), <span class="at">y =</span> RataRating)) <span class="sc">+</span>  <span class="co"># Urut descending</span></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#DC143C"</span>) <span class="sc">+</span></span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(RataRating, <span class="dv">2</span>)), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Rata-Rata Rating per Kategori Usia"</span>, <span class="at">x =</span> <span class="st">"Kategori"</span>, <span class="at">y =</span> <span class="st">"Rating"</span>) <span class="sc">+</span></span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Grafik tersebut menunjukkan rata-rata rating tayangan berdasarkan kategori usia. Tayangan dengan klasifikasi TV-PG memiliki rating tertinggi (7.57), diikuti oleh Unrated dan PG, yang menandakan bahwa tayangan dengan konten ringan atau untuk semua umur lebih disukai penonton. Sebaliknya, kategori usia dewasa seperti TV-MA dan NC-17 justru memiliki rating terendah, mengindikasikan bahwa tayangan dengan konten berat tidak selalu mendapat respons positif. Sementara itu, kategori NA dan Not Rated tetap memperoleh rating cukup baik. Secara umum, tayangan dengan jangkauan audiens yang lebih luas dan konten ramah keluarga cenderung mendapat penilaian lebih tinggi dibandingkan tayangan dewasa.</p>
</section>
<section id="word-cloud-judul-film" class="level3">
<h3 class="anchored" data-anchor-id="word-cloud-judul-film">Word Cloud Judul Film</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>corpus <span class="ot">&lt;-</span> <span class="fu">Corpus</span>(<span class="fu">VectorSource</span>(df_clean<span class="sc">$</span>Title))</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>corpus <span class="ot">&lt;-</span> <span class="fu">tm_map</span>(corpus, <span class="fu">content_transformer</span>(tolower))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tm_map.SimpleCorpus(corpus, content_transformer(tolower)):
transformation drops documents</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>corpus <span class="ot">&lt;-</span> <span class="fu">tm_map</span>(corpus, removePunctuation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tm_map.SimpleCorpus(corpus, removePunctuation): transformation drops
documents</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>corpus <span class="ot">&lt;-</span> <span class="fu">tm_map</span>(corpus, removeNumbers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tm_map.SimpleCorpus(corpus, removeNumbers): transformation drops
documents</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>corpus <span class="ot">&lt;-</span> <span class="fu">tm_map</span>(corpus, removeWords, <span class="fu">stopwords</span>(<span class="st">"english"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tm_map.SimpleCorpus(corpus, removeWords, stopwords("english")):
transformation drops documents</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>dtm <span class="ot">&lt;-</span> <span class="fu">TermDocumentMatrix</span>(corpus)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(dtm)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">rowSums</span>(m), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>df_words <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">word =</span> <span class="fu">names</span>(v), <span class="at">freq =</span> v)</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a><span class="fu">wordcloud</span>(<span class="at">words =</span> df_words<span class="sc">$</span>word, <span class="at">freq =</span> df_words<span class="sc">$</span>freq,</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">min.freq =</span> <span class="dv">2</span>, <span class="at">max.words =</span> <span class="dv">100</span>,</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">random.order =</span> <span class="cn">FALSE</span>, <span class="at">colors =</span> <span class="fu">brewer.pal</span>(<span class="dv">8</span>, <span class="st">"Dark2"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Word cloud tersebut menggambarkan kata-kata yang paling sering muncul dalam judul tayangan atau film, dengan ukuran huruf yang lebih besar menunjukkan frekuensi kemunculan yang lebih tinggi. Terlihat bahwa kata “man” menjadi yang paling dominan, diikuti oleh kata-kata seperti “one”, “last”, “story”, dan “part”. Hal ini menunjukkan bahwa kata “man” sering digunakan dalam judul, yang dapat mencerminkan banyaknya tokoh sentral pria dalam film atau tayangan. Sebaliknya, semakin kecil ukuran tulisan suatu kata, maka semakin jarang kata tersebut muncul dalam judul, yang menunjukkan frekuensi penggunaannya relatif rendah dibandingkan kata-kata lain.</p>
</section>
<section id="pemetaan-kuadran-popularitas-dan-kualitas" class="level3">
<h3 class="anchored" data-anchor-id="pemetaan-kuadran-popularitas-dan-kualitas">Pemetaan Kuadran (Popularitas dan Kualitas)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter data bersih</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>df_clean_filtered <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Rating), <span class="sc">!</span><span class="fu">is.na</span>(VoteNumeric))</span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Hitung rata-rata rating dan vote</span></span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>avg_rating <span class="ot">&lt;-</span> <span class="fu">mean</span>(df_clean_filtered<span class="sc">$</span>Rating, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a>avg_vote <span class="ot">&lt;-</span> <span class="fu">mean</span>(df_clean_filtered<span class="sc">$</span>VoteNumeric, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-13"><a href="#cb78-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Ambil outlier: film dengan vote tinggi &amp; rating rendah atau sebaliknya</span></span>
<span id="cb78-14"><a href="#cb78-14" aria-hidden="true" tabindex="-1"></a>kontroversial <span class="ot">&lt;-</span> df_clean_filtered <span class="sc">%&gt;%</span></span>
<span id="cb78-15"><a href="#cb78-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb78-16"><a href="#cb78-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">kategori =</span> <span class="fu">case_when</span>(</span>
<span id="cb78-17"><a href="#cb78-17" aria-hidden="true" tabindex="-1"></a>      Rating <span class="sc">&gt;=</span> avg_rating <span class="sc">&amp;</span> VoteNumeric <span class="sc">&lt;</span> avg_vote <span class="sc">~</span> <span class="st">"Rating Tinggi, Vote Rendah"</span>,</span>
<span id="cb78-18"><a href="#cb78-18" aria-hidden="true" tabindex="-1"></a>      Rating <span class="sc">&lt;</span> avg_rating <span class="sc">&amp;</span> VoteNumeric <span class="sc">&gt;=</span> avg_vote <span class="sc">~</span> <span class="st">"Rating Rendah, Vote Tinggi"</span>,</span>
<span id="cb78-19"><a href="#cb78-19" aria-hidden="true" tabindex="-1"></a>      Rating <span class="sc">&gt;=</span> avg_rating <span class="sc">&amp;</span> VoteNumeric <span class="sc">&gt;=</span> avg_vote <span class="sc">~</span> <span class="st">"Disukai Banyak Orang"</span>,</span>
<span id="cb78-20"><a href="#cb78-20" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Kurang Dikenal"</span></span>
<span id="cb78-21"><a href="#cb78-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb78-22"><a href="#cb78-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb78-23"><a href="#cb78-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-24"><a href="#cb78-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb78-25"><a href="#cb78-25" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kontroversial, <span class="fu">aes</span>(<span class="at">x =</span> Rating, <span class="at">y =</span> VoteNumeric, <span class="at">color =</span> kategori)) <span class="sc">+</span></span>
<span id="cb78-26"><a href="#cb78-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb78-27"><a href="#cb78-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(</span>
<span id="cb78-28"><a href="#cb78-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> Title),</span>
<span id="cb78-29"><a href="#cb78-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">3.2</span>,</span>
<span id="cb78-30"><a href="#cb78-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">max.overlaps =</span> <span class="dv">20</span>,</span>
<span id="cb78-31"><a href="#cb78-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">box.padding =</span> <span class="fl">0.5</span></span>
<span id="cb78-32"><a href="#cb78-32" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">+</span></span>
<span id="cb78-33"><a href="#cb78-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> avg_rating, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span></span>
<span id="cb78-34"><a href="#cb78-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> avg_vote, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span></span>
<span id="cb78-35"><a href="#cb78-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb78-36"><a href="#cb78-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Rating Tinggi, Vote Rendah"</span> <span class="ot">=</span> <span class="st">"#0072B2"</span>,</span>
<span id="cb78-37"><a href="#cb78-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Rating Rendah, Vote Tinggi"</span> <span class="ot">=</span> <span class="st">"#D55E00"</span>,</span>
<span id="cb78-38"><a href="#cb78-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Disukai Banyak Orang"</span> <span class="ot">=</span> <span class="st">"#009E73"</span>,</span>
<span id="cb78-39"><a href="#cb78-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Kurang Dikenal"</span> <span class="ot">=</span> <span class="st">"pink"</span></span>
<span id="cb78-40"><a href="#cb78-40" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb78-41"><a href="#cb78-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb78-42"><a href="#cb78-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Film Paling Kontroversial Berdasarkan Rating dan Jumlah Vote"</span>,</span>
<span id="cb78-43"><a href="#cb78-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Garis putus-putus menunjukkan rata-rata rating dan vote"</span>,</span>
<span id="cb78-44"><a href="#cb78-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Rating"</span>,</span>
<span id="cb78-45"><a href="#cb78-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Jumlah Vote"</span>,</span>
<span id="cb78-46"><a href="#cb78-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Kategori"</span></span>
<span id="cb78-47"><a href="#cb78-47" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb78-48"><a href="#cb78-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb78-49"><a href="#cb78-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb78-50"><a href="#cb78-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">13</span>),</span>
<span id="cb78-51"><a href="#cb78-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb78-52"><a href="#cb78-52" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb78-53"><a href="#cb78-53" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb78-54"><a href="#cb78-54" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>)</span>
<span id="cb78-55"><a href="#cb78-55" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: ggrepel: 629 unlabeled data points (too many overlaps). Consider
increasing max.overlaps</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Grafik berjudul “Film Paling Kontroversial Berdasarkan Rating dan Jumlah Vote” menampilkan persebaran film berdasarkan dua variabel: rating (sumbu horizontal) dan jumlah vote (sumbu vertikal). Dua garis putus-putus menunjukkan rata-rata kedua variabel tersebut dan membagi grafik menjadi empat kuadran, yang merepresentasikan empat kategori film dengan warna berbeda. Kategori Disukai Banyak Orang (hijau kebiruan) berisi film dengan rating dan vote di atas rata-rata, seperti <em>Oppenheimer</em>, <em>Dune: Part One</em>, dan <em>Barbie</em> — menunjukkan film yang populer sekaligus berkualitas. Kurang Dikenal (pink) mencakup film dengan rating dan vote rendah, seperti <em>A Breed Apart</em>, yang menunjukkan minimnya eksposur dan penerimaan publik. Kategori Rating Rendah, Vote Tinggi (oranye) berisi film seperti <em>Snow White</em> yang meskipun banyak ditonton, mendapat penilaian buruk — mengindikasikan adanya kontroversi atau kekecewaan. Sebaliknya, Rating Tinggi, Vote Rendah (biru) mencakup film berkualitas namun kurang dikenal, berpotensi sebagai <em>hidden gems</em>. Secara keseluruhan, grafik ini membantu mengidentifikasi film-film yang menonjol karena kualitas, kontroversi, atau kurangnya eksposur, serta memberikan gambaran tentang bagaimana publik menilai dan merespons film secara luas.</p>
</section>
<section id="top-film-dengan-rate-tertinggi-per-kategori" class="level3">
<h3 class="anchored" data-anchor-id="top-film-dengan-rate-tertinggi-per-kategori">Top Film dengan Rate Tertinggi per Kategori</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter dan ambil film dengan rating tertinggi per kategori (tanpa NA)</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>top_rating_per_category <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Category)) <span class="sc">%&gt;%</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Category) <span class="sc">%&gt;%</span></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> Rating, <span class="at">n =</span> <span class="dv">1</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualisasi lollipop chart dengan perbaikan teks tidak terpotong</span></span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(top_rating_per_category, <span class="fu">aes</span>(<span class="at">x =</span> Rating, <span class="at">y =</span> <span class="fu">reorder</span>(Category, Rating), <span class="at">color =</span> Category)) <span class="sc">+</span></span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Garis lollipop</span></span>
<span id="cb80-14"><a href="#cb80-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">xend =</span> Rating, <span class="at">yend =</span> <span class="fu">reorder</span>(Category, Rating)), <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb80-15"><a href="#cb80-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Titik lollipop</span></span>
<span id="cb80-16"><a href="#cb80-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb80-17"><a href="#cb80-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Nilai rating di kanan titik</span></span>
<span id="cb80-18"><a href="#cb80-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(Rating, <span class="dv">2</span>)), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.6</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb80-19"><a href="#cb80-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Judul film di atas garis</span></span>
<span id="cb80-20"><a href="#cb80-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> Rating <span class="sc">/</span> <span class="dv">2</span>, <span class="at">label =</span> Title), </span>
<span id="cb80-21"><a href="#cb80-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">1.2</span>, </span>
<span id="cb80-22"><a href="#cb80-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="fl">3.5</span>, </span>
<span id="cb80-23"><a href="#cb80-23" aria-hidden="true" tabindex="-1"></a>            <span class="at">fontface =</span> <span class="st">"italic"</span>, </span>
<span id="cb80-24"><a href="#cb80-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb80-25"><a href="#cb80-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Skala dan koordinat agar tidak terpotong</span></span>
<span id="cb80-26"><a href="#cb80-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.2</span>))) <span class="sc">+</span></span>
<span id="cb80-27"><a href="#cb80-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">clip =</span> <span class="st">"off"</span>) <span class="sc">+</span>  <span class="co"># Ini penting agar teks di luar panel tetap terlihat</span></span>
<span id="cb80-28"><a href="#cb80-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb80-29"><a href="#cb80-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Film dengan Rating Tertinggi per Kategori"</span>,</span>
<span id="cb80-30"><a href="#cb80-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Rating"</span>,</span>
<span id="cb80-31"><a href="#cb80-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="cn">NULL</span></span>
<span id="cb80-32"><a href="#cb80-32" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb80-33"><a href="#cb80-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb80-34"><a href="#cb80-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb80-35"><a href="#cb80-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb80-36"><a href="#cb80-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb80-37"><a href="#cb80-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb80-38"><a href="#cb80-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">20</span>, <span class="dv">20</span>),  <span class="co"># Tambah margin kanan-kiri jika perlu</span></span>
<span id="cb80-39"><a href="#cb80-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span></span>
<span id="cb80-40"><a href="#cb80-40" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Secara umum, grafik ini menunjukkan bahwa kualitas film setidaknya berdasarkan rating tidak selalu berkorelasi langsung dengan tingkat klasifikasi usia. Film-film dari kategori yang tidak dinilai secara resmi seperti Not Rated justru mampu memperoleh rating tinggi, sementara kategori dengan pembatasan ketat seperti NC-17 justru menampilkan film dengan performa rendah. Visualisasi ini memberikan gambaran yang informatif mengenai bagaimana performa film terbaik dari setiap kategori sensor dalam hal penilaian oleh penonton.</p>
</section>
<section id="top-film-dengan-vote-tertinggi-per-kategori" class="level3">
<h3 class="anchored" data-anchor-id="top-film-dengan-vote-tertinggi-per-kategori">Top Film dengan Vote Tertinggi per Kategori</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ambil film dengan vote tertinggi per kategori</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>top_vote_per_category <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Category)) <span class="sc">%&gt;%</span></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Category) <span class="sc">%&gt;%</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> VoteNumeric, <span class="at">n =</span> <span class="dv">1</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Lollipop chart: Judul film di samping kanan titik</span></span>
<span id="cb82-12"><a href="#cb82-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(top_vote_per_category, <span class="fu">aes</span>(<span class="at">x =</span> VoteNumeric, <span class="at">y =</span> <span class="fu">reorder</span>(Category, VoteNumeric), <span class="at">color =</span> Category)) <span class="sc">+</span></span>
<span id="cb82-13"><a href="#cb82-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">xend =</span> VoteNumeric, <span class="at">yend =</span> <span class="fu">reorder</span>(Category, VoteNumeric)), <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb82-14"><a href="#cb82-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb82-15"><a href="#cb82-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(Title, <span class="st">" ("</span>, scales<span class="sc">::</span><span class="fu">comma</span>(VoteNumeric), <span class="st">" votes)"</span>)),</span>
<span id="cb82-16"><a href="#cb82-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="dv">0</span>,  <span class="co"># teks tepat di kanan titik</span></span>
<span id="cb82-17"><a href="#cb82-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">nudge_x =</span> <span class="dv">30000</span>,  <span class="co"># geser teks ke kanan dari titik</span></span>
<span id="cb82-18"><a href="#cb82-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">fontface =</span> <span class="st">"italic"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb82-19"><a href="#cb82-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb82-20"><a href="#cb82-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Skala diperluas di sisi kanan (misal, maksimum vote + margin)</span></span>
<span id="cb82-21"><a href="#cb82-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb82-22"><a href="#cb82-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(top_vote_per_category<span class="sc">$</span>VoteNumeric) <span class="sc">*</span> <span class="fl">1.2</span>),</span>
<span id="cb82-23"><a href="#cb82-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> scales<span class="sc">::</span>comma,</span>
<span id="cb82-24"><a href="#cb82-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb82-25"><a href="#cb82-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb82-26"><a href="#cb82-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">clip =</span> <span class="st">"off"</span>) <span class="sc">+</span></span>
<span id="cb82-27"><a href="#cb82-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb82-28"><a href="#cb82-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb82-29"><a href="#cb82-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Film dengan Jumlah Vote Tertinggi per Kategori"</span>,</span>
<span id="cb82-30"><a href="#cb82-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Jumlah Vote"</span>,</span>
<span id="cb82-31"><a href="#cb82-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="cn">NULL</span></span>
<span id="cb82-32"><a href="#cb82-32" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb82-33"><a href="#cb82-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb82-34"><a href="#cb82-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb82-35"><a href="#cb82-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb82-36"><a href="#cb82-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb82-37"><a href="#cb82-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb82-38"><a href="#cb82-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="dv">20</span>, <span class="dv">100</span>, <span class="dv">20</span>, <span class="dv">20</span>),  <span class="co"># Tambahkan margin kanan (kanan=100)</span></span>
<span id="cb82-39"><a href="#cb82-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span></span>
<span id="cb82-40"><a href="#cb82-40" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretasi:</p>
<p>Grafik tersebut menunjukkan film dengan jumlah vote tertinggi pada setiap kategori usia. Terlihat bahwa kategori PG-13 dan R mendominasi dengan jumlah vote yang sangat tinggi, yaitu <em>Dune: Part One</em> (958.000 vote) dan <em>Oppenheimer</em> (893.000 vote). Sementara itu, kategori PG juga menonjol dengan <em>Spider-Man: Across the Spider-Verse</em> (457.000 vote). Sebaliknya, kategori seperti 16+, TV-PG, dan Unrated menunjukkan film dengan jumlah vote yang jauh lebih rendah, seperti <em>The Coffee Table</em> (10.000 vote) dan <em>Benedetta</em> (28.000 vote). Hal ini menunjukkan bahwa film dengan kategori usia yang lebih umum (seperti PG-13 dan R) cenderung memiliki jangkauan penonton lebih luas dan lebih populer dibandingkan kategori yang lebih terbatas.</p>
</section>
<section id="top-3-film-dengan-rate-tertinggi-per-tahun" class="level3">
<h3 class="anchored" data-anchor-id="top-3-film-dengan-rate-tertinggi-per-tahun">TOP 3 Film dengan Rate Tertinggi per tahun</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Ambil top 3 film per tahun</span></span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>top3_per_year <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> Rating, <span class="at">n =</span> <span class="dv">3</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-11"><a href="#cb83-11" aria-hidden="true" tabindex="-1"></a>years <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(top3_per_year<span class="sc">$</span>Year))</span>
<span id="cb83-12"><a href="#cb83-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-13"><a href="#cb83-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Tentukan manual warna (pastikan jumlah warna &gt;= jumlah tahun)</span></span>
<span id="cb83-14"><a href="#cb83-14" aria-hidden="true" tabindex="-1"></a>custom_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb83-15"><a href="#cb83-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#e74c3c"</span>,  <span class="co"># red</span></span>
<span id="cb83-16"><a href="#cb83-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#3498db"</span>,  <span class="co"># blue ocean</span></span>
<span id="cb83-17"><a href="#cb83-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#9b59b6"</span>,  <span class="co"># purple</span></span>
<span id="cb83-18"><a href="#cb83-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#fd79a8"</span>,  <span class="co"># pink</span></span>
<span id="cb83-19"><a href="#cb83-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#1abc9c"</span>,  <span class="co"># tosca</span></span>
<span id="cb83-20"><a href="#cb83-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#f39c12"</span>,  <span class="co"># tambahan jika tahun lebih dari 5</span></span>
<span id="cb83-21"><a href="#cb83-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#2ecc71"</span>   <span class="co"># tambahan lain (hijau lembut)</span></span>
<span id="cb83-22"><a href="#cb83-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb83-23"><a href="#cb83-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-24"><a href="#cb83-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Mapping warna ke tahun</span></span>
<span id="cb83-25"><a href="#cb83-25" aria-hidden="true" tabindex="-1"></a>colors_year <span class="ot">&lt;-</span> <span class="fu">setNames</span>(custom_colors[<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(years)], years)</span>
<span id="cb83-26"><a href="#cb83-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-27"><a href="#cb83-27" aria-hidden="true" tabindex="-1"></a>plot_per_year <span class="ot">&lt;-</span> <span class="cf">function</span>(yr) {</span>
<span id="cb83-28"><a href="#cb83-28" aria-hidden="true" tabindex="-1"></a>  data_year <span class="ot">&lt;-</span> top3_per_year <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year <span class="sc">==</span> yr)</span>
<span id="cb83-29"><a href="#cb83-29" aria-hidden="true" tabindex="-1"></a>  col <span class="ot">&lt;-</span> colors_year[<span class="fu">as.character</span>(yr)]  <span class="co"># warna khusus untuk tahun ini</span></span>
<span id="cb83-30"><a href="#cb83-30" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb83-31"><a href="#cb83-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(data_year, <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">reorder</span>(Title, Rating), <span class="at">x =</span> Rating)) <span class="sc">+</span></span>
<span id="cb83-32"><a href="#cb83-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">xend =</span> Rating, <span class="at">yend =</span> Title), <span class="at">color =</span> col, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb83-33"><a href="#cb83-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">5</span>, <span class="at">color =</span> col) <span class="sc">+</span></span>
<span id="cb83-34"><a href="#cb83-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> Rating <span class="sc">/</span> <span class="dv">2</span>, <span class="at">label =</span> Title), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">1.2</span>, <span class="at">size =</span> <span class="dv">6</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>, <span class="at">color =</span> col) <span class="sc">+</span></span>
<span id="cb83-35"><a href="#cb83-35" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(Rating, <span class="dv">1</span>)), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.9</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb83-36"><a href="#cb83-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.2</span>))) <span class="sc">+</span></span>
<span id="cb83-37"><a href="#cb83-37" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb83-38"><a href="#cb83-38" aria-hidden="true" tabindex="-1"></a>      <span class="at">title =</span> <span class="fu">paste</span>(yr),</span>
<span id="cb83-39"><a href="#cb83-39" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Rating"</span>,</span>
<span id="cb83-40"><a href="#cb83-40" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="cn">NULL</span></span>
<span id="cb83-41"><a href="#cb83-41" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb83-42"><a href="#cb83-42" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb83-43"><a href="#cb83-43" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb83-44"><a href="#cb83-44" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb83-45"><a href="#cb83-45" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb83-46"><a href="#cb83-46" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">17</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb83-47"><a href="#cb83-47" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position =</span> <span class="st">"none"</span></span>
<span id="cb83-48"><a href="#cb83-48" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb83-49"><a href="#cb83-49" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb83-50"><a href="#cb83-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-51"><a href="#cb83-51" aria-hidden="true" tabindex="-1"></a><span class="fu">walk</span>(years, <span class="sc">~</span><span class="fu">print</span>(<span class="fu">plot_per_year</span>(.x)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-33-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-33-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-33-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-33-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Kelompok-2-Mongo-DB_files/figure-html/unnamed-chunk-33-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>